=== Bgabor-prog/QVTQO8_XML.Gyak/Feleves_Task/XMLSchemeQVTQO8.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Tulaj" type="TulajType"/>
    <!-- 
      Konyveloiroda element létrehozása
    -->
    
    <xs:complexType name="KonyveloirodaType">
      <xs:sequence>
        <xs:element type="szekhelyType" name="szekhely"/>
        <xs:element type="xs:string" name="ugyvezeto"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="k_adoszam" use="optional"/>
    </xs:complexType>
  
  <!-- 
    Ceg element létrehozása
   -->
  <xs:complexType name="CegType">
    <xs:sequence>
      <xs:element type="xs:string" name="email"/>
      <xs:element type="xs:string" name="szekhely"/>
      <xs:element type="xs:short" name="alapitas_eve"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="nev" use="optional"/>
    <xs:attribute type="xs:string" name="u_c" use="optional"/>
  </xs:complexType>

  <!-- 
    Ugyfelek element létrehozása
   -->
  <xs:complexType name="UgyfelekType">
    <xs:sequence>
      <xs:element type="xs:string" name="nev"/>
      <xs:element type="xs:string" name="email"/>
      <xs:element type="lakcimType" name="lakcim"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="u_adoazonosito" use="optional"/>
    <xs:attribute type="xs:string" name="k_u" use="optional"/>
  </xs:complexType>

  <!-- 
    Nav element létrehozása
   -->
  <xs:complexType name="NavType">
    <xs:sequence>
      <xs:element type="xs:string" name="email"/>
      <xs:element type="ugyintezoType" name="ugyintezo"/>
      <xs:element type="nyitvatartasType" name="nyitvatartas"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="n_adoszam" use="optional"/>
    <xs:attribute type="xs:string" name="k_n" use="optional"/>
  </xs:complexType>

  <!-- 
   Oep element létrehozása
  -->
  <xs:complexType name="OepType">
    <xs:sequence>
      <xs:element type="xs:string" name="email"/>
      <xs:element type="ugyintezoType" name="ugyintezo"/>
      <xs:element type="nyitvatartasType" name="nyitvatartas"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="o_adoszam" use="optional"/>
    <xs:attribute type="xs:string" name="k_o" use="optional"/>
  </xs:complexType>

  <!-- 
    Onkormanyzat element létrehozása
   -->
  <xs:complexType name="OnkormanyzatType">
    <xs:sequence>
      <xs:element type="xs:string" name="email"/>
      <xs:element type="ugyintezoType" name="ugyintezo"/>
      <xs:element type="nyitvatartasType" name="nyitvatartas"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="on_adoszam" use="optional"/>
  </xs:complexType>

  <xs:complexType name="Konyv_OnkType">
    <xs:sequence>
      <xs:element type="xs:int" name="dok.id"/>
      <xs:element type="xs:byte" name="dok.szam"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="k_on" use="optional"/>
    <xs:attribute type="xs:string" name="k_k" use="optional"/>
  </xs:complexType>
  
  <!-- 
    Complext típusu elemek definiálása
   -->

   <xs:complexType name="szekhelyType">
    <xs:sequence>
      <xs:element type="xs:short" name="irszam"/>
      <xs:element type="xs:byte" name="hazszam"/>
      <xs:element type="xs:string" name="utca"/>
      <xs:element type="xs:string" name="varos"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="lakcimType">
    <xs:sequence>
      <xs:element type="xs:short" name="irszam"/>
      <xs:element type="xs:short" name="hazszam"/>
      <xs:element type="xs:string" name="utca"/>
      <xs:element type="xs:string" name="varos"/>
    </xs:sequence>
  </xs:complexType>

   <xs:complexType name="ugyintezoType">
    <xs:sequence>
      <xs:element type="xs:string" name="email"/>
      <xs:element type="xs:long" name="telefon"/>
      <xs:element type="xs:string" name="nev"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="nyitvatartasType">
    <xs:sequence>
      <xs:element type="xs:string" name="tol"/>
      <xs:element type="xs:string" name="ig"/>
    </xs:sequence>
  </xs:complexType>

  <!-- 
    Egyedi tipusok meghatározása
   -->
  <xs:complexType name="TulajType">
    <xs:sequence>

      <xs:element type="KonyveloirodaType" name="Konyveloiroda" maxOccurs="unbounded" minOccurs="3">
      </xs:element>

      <xs:element type="CegType" name="Ceg" maxOccurs="unbounded" minOccurs="3">
      </xs:element>

      <xs:element type="UgyfelekType" name="Ugyfelek" maxOccurs="unbounded" minOccurs="3">   
      </xs:element>

      <xs:element type="NavType" name="Nav" maxOccurs="unbounded" minOccurs="3">       
      </xs:element>

      <xs:element type="OepType" name="Oep" maxOccurs="unbounded" minOccurs="3">
      </xs:element>

      <xs:element type="OnkormanyzatType" name="Onkormanyzat" maxOccurs="unbounded" minOccurs="3">  
      </xs:element>

      <xs:element type="Konyv_OnkType" name="Konyv_Onk" maxOccurs="unbounded" minOccurs="3">
      </xs:element>  
    </xs:sequence>
  </xs:complexType>

  <xs:element name="keys">
      <!-- 
            Konyvelo iroda primary key majd foreign kapcsolatok kialakítása
         -->
         <xs:key name="Konyveliroda_kulcs">
          <xs:selector xpath="Konyveloiroda"></xs:selector>
          <xs:field xpath="@k_adoszam"></xs:field>
      </xs:key>

      <xs:keyref refer="Konyveliroda_kulcs" name="könyveloiroda_ceg_f_key">
          <xs:selector xpath="Ceg"></xs:selector>
          <xs:field xpath="@u_c"></xs:field>
      </xs:keyref>

      <xs:keyref refer="Konyveliroda_kulcs" name="könyveloiroda_ugyfel_f_key">
          <xs:selector xpath="Ugyfelek"></xs:selector>
          <xs:field xpath="@k_u"></xs:field>
      </xs:keyref>

      <xs:keyref refer="Konyveliroda_kulcs" name="könyveloiroda_nav_f_key">
          <xs:selector xpath="Nav"></xs:selector>
          <xs:field xpath="@k_n"></xs:field>
      </xs:keyref>

      <xs:keyref refer="Konyveliroda_kulcs" name="könyveloiroda_oep_f_key">
          <xs:selector xpath="Oep"></xs:selector>
          <xs:field xpath="@k_o"></xs:field>
      </xs:keyref>

      <!-- 
          Konyveloiroda és az onkormányzat közötti tobb-tobb kapcs. kialakítása
       -->
      <xs:key name="Onkormanyzat_kulcs">
          <xs:selector xpath="Onkormanyzat"></xs:selector>
          <xs:field xpath="@on_adoszam"></xs:field>
      </xs:key>

      <xs:keyref refer="Onkormanyzat_kulcs" name="Onkormanyzat_konyveloiroda_f_key">
          <xs:selector xpath="Konyv_Onk"></xs:selector>
          <xs:field xpath="@k_on"></xs:field>
      </xs:keyref>

      <xs:keyref refer="Konyveliroda_kulcs" name="könyveloiroda_onkormanyzat_f_key">
          <xs:selector xpath="Konyv_Onk"></xs:selector>
          <xs:field xpath="@k_k"></xs:field>
      </xs:keyref>
  </xs:element>
</xs:schema>

=== Bgabor-prog/QVTQO8_XML.Gyak/Feleves_Task/XMLQVTQO8.xml
<?xml version="1.0" encoding="UTF-8"?>

<Tulaj xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemeQVTQO8.xsd">
    
    <!-- 
        Konyveloirodak
     -->
    <Konyveloiroda k_adoszam="k1">
        <szekhely>
            <irszam>2673</irszam>
            <hazszam>55</hazszam>
            <utca>Kakora</utca>
            <varos>Pingalo</varos>
        </szekhely>
        <ugyvezeto>Vigaldi Béla</ugyvezeto>
    </Konyveloiroda>
    
    <Konyveloiroda k_adoszam="k2">
        <szekhely>
            <irszam>2345</irszam>
            <hazszam>21</hazszam>
            <utca>Papír utca</utca>
            <varos>Eifengel</varos>
        </szekhely>
        <ugyvezeto> Pakula Anna </ugyvezeto>
    </Konyveloiroda>
    
    <Konyveloiroda k_adoszam="k3">
        <szekhely>
            <irszam>8654</irszam>
            <hazszam>81</hazszam>
            <utca>Tengi</utca>
            <varos>Spank</varos>
        </szekhely>
        <ugyvezeto>Dekt Elek</ugyvezeto>
    </Konyveloiroda>

    <!-- 
        Cegek
     -->
    <Ceg nev="egy" u_c="u1">
        <email>cegecske@portal.hu</email>
        <szekhely>Karácsony</szekhely>
        <alapitas_eve>1144</alapitas_eve>
    </Ceg>

    <Ceg nev="ketto" u_c="u2">
        <email>kapucsinalo@portal.hu</email>
        <szekhely>Husvet</szekhely>
        <alapitas_eve>1450</alapitas_eve>
    </Ceg>

    <Ceg nev="harom" u_c="u3">
        <email>lakatos@portal.hu</email>
        <szekhely>Ujev</szekhely>
        <alapitas_eve>1888</alapitas_eve>
    </Ceg>

    <!-- 
        Ugyfelek
     -->
    <Ugyfelek u_adoazonosito="u1" k_u="k1">
        <nev>Higo Hugo</nev>
        <email>asdasd@vaefl.hu</email>
        <lakcim>
            <irszam>8431</irszam>
            <hazszam>515</hazszam>
            <utca>Hajgu</utca>
            <varos>Vabuga</varos>
        </lakcim>
    </Ugyfelek>

    <Ugyfelek u_adoazonosito="u2" k_u="k2">
        <nev>Verdes Elek</nev>
        <email>hagusfa@gmail.com</email>
        <lakcim>
            <irszam>1020</irszam>
            <hazszam>11</hazszam>
            <utca>Pecsét</utca>
            <varos>Irat</varos>
        </lakcim>
    </Ugyfelek>

    <Ugyfelek u_adoazonosito="u3" k_u="k3">
        <nev>Paktum Patrik</nev>
        <email>ppatrik@freemail.com</email>
        <lakcim>
            <irszam>6723</irszam>
            <hazszam>25</hazszam>
            <utca>Derped</utca>
            <varos>Rekedt</varos>
        </lakcim>
    </Ugyfelek>

    <!-- 
        Nav
     -->
    <Nav n_adoszam="n1" k_n="k1">
        <email>idekuld@nav.hu</email>
        <ugyintezo>
            <email>esztikeh@nav.hu</email>
            <telefon>06304672056</telefon>
            <nev>Galamb Eszter</nev>
        </ugyintezo>
        <nyitvatartas>
            <tol>8:00</tol>
            <ig>12:00</ig>
        </nyitvatartas>
    </Nav>

    <Nav n_adoszam="n2" k_n="k1">
        <email>idekuld@nav.hu</email>
        <ugyintezo>
            <email>pistikehgh@nav.hu</email>
            <telefon>06304623656</telefon>
            <nev>Vad Péter</nev>
        </ugyintezo>
        <nyitvatartas>
            <tol>8:00</tol>
            <ig>12:00</ig>
        </nyitvatartas>
    </Nav>

    <Nav n_adoszam="n3" k_n="k1">
        <email>idekuld@nav.hu</email>
        <ugyintezo>
            <email>andikah@nav.hu</email>
            <telefon>06307353456</telefon>
            <nev>Emb Andrea</nev>
        </ugyintezo>
        <nyitvatartas>
            <tol>8:00</tol>
            <ig>12:00</ig>
        </nyitvatartas>
    </Nav>

    <!-- 
        Oep
     -->
    <Oep o_adoszam="o1" k_o="k1">
        <email>erreküld@oep.hu</email>
        <ugyintezo>
            <email>ronaldinho@oep.hu</email>
            <telefon>06705684050</telefon>
            <nev>Ricardo Ronaldinho</nev>
        </ugyintezo>
        <nyitvatartas>
            <tol>7:00</tol>
            <ig>16:00</ig>
        </nyitvatartas>
    </Oep>

    <Oep o_adoszam="o2" k_o="k2">
        <email>erreküld@oep.hu</email>
        <ugyintezo>
            <email>inez@oep.hu</email>
            <telefon>06707357246</telefon>
            <nev>Kardos Inez</nev>
        </ugyintezo>
        <nyitvatartas>
            <tol>8:00</tol>
            <ig>16:00</ig>
        </nyitvatartas>
    </Oep>

    <Oep o_adoszam="o3" k_o="k3">
        <email>erreküld@oep.hu</email>
        <ugyintezo>
            <email>hemb.sanyi@oep.hu</email>
            <telefon>06709741456</telefon>
            <nev>Hemb Sándor</nev>
        </ugyintezo>
        <nyitvatartas>
            <tol>7:00</tol>
            <ig>16:00</ig>
        </nyitvatartas>
    </Oep>

    <!-- 
        Onkormanyzatok
     -->
    <Onkormanyzat on_adoszam="on1">
        <email>külddide@onk.hu</email>
        <ugyintezo>
            <email>purhab@onk.hu</email>
            <telefon>06209782132</telefon>
            <nev>Pur Hab</nev>
        </ugyintezo>
        <nyitvatartas>
            <tol>9:00</tol>
            <ig>13:30</ig>
        </nyitvatartas>
    </Onkormanyzat>

    <Onkormanyzat on_adoszam="on2">
        <email>külddide@onk.hu</email>
        <ugyintezo>
            <email>tali.cska@onk.hu</email>
            <telefon>06203145469</telefon>
            <nev>Tali Cska</nev>
        </ugyintezo>
        <nyitvatartas>
            <tol>9:00</tol>
            <ig>13:30</ig>
        </nyitvatartas>
    </Onkormanyzat>

    <Onkormanyzat on_adoszam="on3">
        <email>külddide@onk.hu</email>
        <ugyintezo>
            <email>szekereszter@onk.hu</email>
            <telefon>06207132875</telefon>
            <nev>Szeker Eszter</nev>
        </ugyintezo>
        <nyitvatartas>
            <tol>9:00</tol>
            <ig>13:30</ig>
        </nyitvatartas>
    </Onkormanyzat>

    <!-- 
        Konyvelo iroda és az onkormányzat közötti több-több kapcsolat segéd példányai
     -->
    <Konyv_Onk k_on="on1" k_k="k1">
        <dok.id>254123</dok.id>
        <dok.szam>3</dok.szam>
    </Konyv_Onk>

    <Konyv_Onk k_on="on2" k_k="k2">
        <dok.id>673773</dok.id>
        <dok.szam>5</dok.szam>
    </Konyv_Onk>

    <Konyv_Onk k_on="on3" k_k="k3">
        <dok.id>982515</dok.id>
        <dok.szam>1</dok.szam>
    </Konyv_Onk>

</Tulaj>
